### ISSUE TITLE
For new blockScraper data formats

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#226]
MOVE TO ISSUE #397 

```
[x] ./<cache>/                          [x] ~/.quickBlocks/
[x]    |--------fullBlockIndex.bin      [x]    |--------slurps/
[x]    |--------miniBlocks.bin          [x]    |--------abis/
[x]    |--------miniTrans.bin           [x]    |--------names (moved to <cache>)/
[x]    |--------prices                  [x] ./monitors/
[x]    |--------blocks/00               [x]    |--------<acct>/cache/
[x]    |--------blooms/00               [x] ./other/acctIndex
```

#### OPEN
- [ ] #25 Compare old data to new. What changed? This is last chance to explore chain re-orgs.
-- `receipt.logs.logIndex` used to be incorrect in Parity. This might change in old blocks.
- [ ] #162 All binary data must use exitHandlers to delete lock file if quitting early.
- [ ] #313 Collect statistics prior to upgrading binary databases

**Comment by tjayrush** [comment]
#### CLOSED
- [x] ~~Change accessibility (getters/setters) to the data from the class perspective~~
- [x] ~~#24 BLOCK_CACHE has to be made arbitrary and not fixed~~
- [x] ~~Preserve old data until all testing is done.~~
- [x] ~~Surround as much of the data with tests and statistics as possible before starting~~
- [x] ~~Stats: nTrans per block, nError trans per block, nTraces per trans, nLogs per receipt, nFiles, nBytes, nBloom files, nBloom bytes~~

**Comment by tjayrush** [comment]
Closing. Moved to #397
