### ISSUE TITLE
Project Management

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#262]
**Other Project Management Issues Closed until after 0.2.0**

- [ ] #279 How To Do Things project-management
- [ ] #231 Logging in to remote Ubuntu and doing 'git push' build-testing project-management type-question
- [ ] #181 Setting up an Ethereum node build-cmake project-management type-question

**Each issue belongs to a Project. These correspond to the folders in the code:**

[ [Libraries](https://github.com/Great-Hill-Corporation/quickBlocks/projects/1) ], [ [Apps](https://github.com/Great-Hill-Corporation/quickBlocks/projects/2) ], [ [Tools](https://github.com/Great-Hill-Corporation/quickBlocks/projects/3) ], [ [Monitors](https://github.com/Great-Hill-Corporation/quickBlocks/projects/4) ], [ [Build](https://github.com/Great-Hill-Corporation/quickBlocks/projects/6) ]

**Each issue should have a status assigned to it. Here are the meanings of each status**

| Status | Meaning |
|--------|---------|
| [inprocess](https://github.com/Great-Hill-Corporation/quickBlocks/issues?q=is%3Aopen+is%3Aissue+label%3Astatus-inprocess) | Issues I am actively working on. |
| [next](https://github.com/Great-Hill-Corporation/quickBlocks/issues?q=is%3Aopen+is%3Aissue+label%3Astatus-next) | Issues I will work on next.<br>Explore these. If you find something you can help on, let me know |
| [verified](https://github.com/Great-Hill-Corporation/quickBlocks/issues?q=is%3Aopen+is%3Aissue+label%3Astatus-verified) | Verified issues that are neither `inprocess` nor `next`.<br>Explore these. If you find something you can help on, let me know |
| [discuss](https://github.com/Great-Hill-Corporation/quickBlocks/issues?q=is%3Aopen+is%3Aissue+label%3Astatus-discuss) | Issues I want to discuss on our next phone call. These are mostly assigned to you. |
| [resolved](https://github.com/Great-Hill-Corporation/quickBlocks/issues?q=is%3Aopen+is%3Aissue+label%3Astatus-resolved) | Any issues that I think are ready to be closed (or are already closed). These will mostly be assigned to the originator of the issue. |
| [delayed](https://github.com/Great-Hill-Corporation/quickBlocks/issues?q=is%3Aopen+is%3Aissue+label%3Astatus-delayed) | Issues that can wait until version 0.5.0 |
| [project<br>management](https://github.com/Great-Hill-Corporation/quickBlocks/issues?q=is%3Aopen+is%3Aissue+label%3Aproject-management) | Issues related to the project |

**Comment by tjayrush** [comment]
100% agree. We can use this issue. I changed the title and made a new tag 'project-management.' Great idea.

**Comment by tjayrush** [comment]
Because I need to range across the entire repo making changes to many files at a time, please enter below what part of the code you will be working on for a given day. When you're finished add 'Done.' or 'Finished' to the line. Such as

     2017-08-25: Working on ethslurp --- and then 'Done' when you quit for the day.

**Comment by tjayrush** [comment]
**For Carlos as of Friday, August 25, 2017**

Please close all [resolved](https://github.com/Great-Hill-Corporation/quickBlocks/issues?q=is%3Aopen+is%3Aissue+label%3Astatus-resolved) issues if you agree that they are resolved.

Please close all [delayed](https://github.com/Great-Hill-Corporation/quickBlocks/issues?q=is%3Aopen+is%3Aissue+label%3Astatus-delayed) issues that are assigned to you. I created #293 to track delayed issues until version 0.5.0. I will re-open them when we're done with release 0.2.0.

**Comment by crodnun** [comment]
For the moment I will only work on the following items:

1) Current issues assigned to me
2) Learning
3) Test cases for ethslurp.

No more

**Comment by tjayrush** [comment]
I am working toward finishing Release 0.2.0. As soon as I finish my 13 remaining issues (and any new ones you open), I can release 0.2.0. Once I do that, I can announce it on Reddit, so hopefully we'll start getting some attention.

For me, the most pressing issue is to get quickBlocks running against a Parity node on another machine. This week, I would like you to focus on getting quickBlocks running on your hosted machine.

Also, I want you to focus on the testrpc. Maybe not to get it actually working, just so we can start understand what, if anything, the test-rpc can do for us.

You may try to finish up ethslurp testing. Once that's done, most of the rest of the tools/apps need a running node to work. Most of the bugs you write against the tools/apps will probably be delayed until after we release 0.2.0, but they are all good bugs so far. I feel like my code is getting very significantly better, and very most thanks to you. Keep up the great work.

For my part, I am going to try to close all 13 remaining issues this week. One of them (#226) had a ton of sub-issues.

I will speak to you at 9:30 am (my time) tomorrow morning. I posted all of my code up to github, so everything I have is now in place. I did have to post changes to the 'ethslurp' code, CMakeLists.txt file, and test cases, so hopefully that doesn't mess you up too much. Let me know.

**Comment by tjayrush** [comment]
Delayed as per #293

**Comment by tjayrush** [comment]
Closing
