### ISSUE TITLE
Statistics needed for binary data upgrade

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#313]
- [ ] #158 How many bytes are currently stored in bloom filters in blocks vs. transactions? 
- [ ] #199 Number of One Hit Wonders
- [ ] Stats:
-- nTrans per block
-- nError trans per block
-- nTraces per trans
-- nLogs per receipt
-- nFiles
-- nBytes
-- nBloom files
-- nBloom bytes
- [x] ~~Preserve old data until all testing is done. Documented in #226.~~
- [x] ~~Surround as much of the data with tests and statistics as possible before starting. Documented in #226.~~

**Comment by tjayrush** [comment]
Close as part of #226

**Comment by tjayrush** [comment]
#293
