### ISSUE TITLE
Issues related to upgrading data

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#397]
#### OPEN
- [x] #25 Compare old data to new. What changed? This is last chance to explore chain re-orgs.
-- `receipt.logs.logIndex` used to be incorrect in Parity. This might change in old blocks.
- [x] #162 All binary data must use exitHandlers to delete lock file if quitting early.
- [x] #313 Collect statistics prior to upgrading binary databases

#### CLOSED
- [x] ~~Change accessibility (getters/setters) to the data from the class perspective~~ (not yet)
- [x] Use ethName, acctIndex, ethPrice, and ethSlurp as examples of upgrading the data files before doing the blocks.
- [x] Preserve old data until all testing is done.
- [x] Surround as much of the data with tests and statistics as possible before starting
- [x] Stats: nTrans per block, nError trans per block, nTraces per trans, nLogs per receipt, nFiles, nBytes, nBloom files, nBloom bytes
- [x] Store bloom at the trace level not the block level.
- [x] ~~All binary data should have versioning~~ (it already does)
- [x] Renumber blooms to by block.txID.traceID (i.e. 4102010.10.2) (no need to track this)
- [x] Learn how to work with 'geth' traces
- [x] If a parent class holds data, don't store it in the base class--ever. (Breaks ethslurp.)
- [x] Bloom filters should be stored in a separate file per block, otherwise regular opening is slower (I don't even know what this means)
- [x] #21 Serialize in derived classes does not check parent's return value
- [x] #24 BLOCK_CACHE has to be made arbitrary and not fixed
- [x] #31 blockScrape --deep --check
- [x] #61 All binary file opening must be protected with the CShareResource class
- [x] #68 Header information, including versioning, for every binary cache (any type)
- [x] #140 First time blockScraper runs it runs silently until block 47,000
- [x] #148 blockScrape -fl does not check for lock file
- [x] #151 Blocks stored below block 50,000 are messed up (not true as per ./below0050000)
- [x] #153 blockScraper, if the files are locked, proceeds anyway without really showing a useful message.
- [x] #159 ethName should store a binary backing cache
- [x] #228 ethPrice hardcodes its data location in the library, it should look it up from a config file with a default. (As should all other databases.)
- [x] #240 CBaseNode should store a timestamp called `lastModified` (unless it takes up too much space--do an estimate)
- [x] #247 Allow for upgrading of binary files on the fly (or at least understand the issue).
- [x] #315 Complete binary upgradability with prices/poloniex.bin is first since it's self contained.
- [x] #386 Ethslurp slurps can be stored in the binary cache folders

#### DELAYED
- [x] #154 Traces larger than 5megabytes (5b5b5b5b5b5 in them) are skipped. Fix this.
- [x] #221 Trace optimizations I - Store nTraces in transaction. Only scan if < BIG unless --deep
- [x] #222 Trace optimizations II - Most time is parsing traces. If > BIG stored pre-parsed traces
- [x] #223 Bloom optimizations - Hierarchical, enhanced, blooms.
- [x] #388 Store some mining data (at least address and probably reward)
- [x] #389  Store 'badTrans' flag in transactions and cache traces for bad transactions (all traces for both in error and not in error)

**Comment by tjayrush** [comment]
Closed for #293
